/*
 * generated by Xtext 2.12.0
 */
package org.inca.integration.souffle.ui.contentassist


/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
class LangProposalProvider extends AbstractLangProposalProvider {
}
