/*
 * generated by Xtext 2.12.0
 */
package org.inca.integration.souffle


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class LangRuntimeModule extends AbstractLangRuntimeModule {
}
